export enum AppPermission {
  SystemAdmin = 'system.admin',

  OnCallTi = 'on-call.ti',
  OnCallDevOps = 'on-call.devops',

  QualityOnCallRead = 'quality.on-call.read',
  QualityOnCallManage = 'quality.on-call.manage',
  QualityDatesRead = 'quality.dates.read',
  QualityDatesManage = 'quality.dates.manage',

  TicketsRead = 'tickets.read',
  TicketsCreate = 'tickets.create',
  TicketsEdit = 'tickets.edit',
  TicketsClassify = 'tickets.classify',
  TicketsExecute = 'tickets.execute',
  TicketsHold = 'tickets.hold',
  TicketsReject = 'tickets.reject',
  TicketsClose = 'tickets.close',
  TicketsAudit = 'tickets.audit',
  TicketsRadio = 'tickets.radio',
  TicketsRecurrenceCreate = 'tickets.recurrence.create',
  TicketsTimelineRead = 'tickets.timeline.read',

  DevOpsProjectsRead = 'devops.projects.read',
  DevOpsProjectsCreate = 'devops.projects.create',
  DevOpsProjectsEdit = 'devops.projects.edit',
  DevOpsTasksRead = 'devops.tasks.read',
  DevOpsTasksCreate = 'devops.tasks.create',
  DevOpsTasksEdit = 'devops.tasks.edit',

  MarketingTasksRead = 'marketing.tasks.read',
  MarketingTasksCreate = 'marketing.tasks.create',
  MarketingTasksEdit = 'marketing.tasks.edit',
  MarketingTasksHold = 'marketing.tasks.hold',
  MarketingTasksClose = 'marketing.tasks.close',

  ReportsRead = 'reports.read',
  ReportsPdf = 'reports.pdf',

  TicketsDevOpsRead = 'tickets.devops.read',
  TicketsDevOpsCreate = 'tickets.devops.create',
  TicketsMarketingRead = 'tickets.marketing.read',
  TicketsMarketingCreate = 'tickets.marketing.create',

  CatalogManage = 'catalog.manage',
  CatalogTiRead = 'catalog.ti.read',
  CatalogTiCreate = 'catalog.ti.create',
  CatalogTiEdit = 'catalog.ti.edit',
  CatalogDevOpsRead = 'catalog.devops.read',
  CatalogDevOpsCreate = 'catalog.devops.create',
  CatalogDevOpsEdit = 'catalog.devops.edit',

  UsersRead = 'users.read',
  UsersCreate = 'users.create',
  UsersEdit = 'users.edit',
  UsersManageAccess = 'users.manage-access',
  UsersAssignRole = 'users.assign-role',
  UsersManageOverrides = 'users.manage-overrides',

  RegistrationsClientsRead = 'registrations.clients.read',
  RegistrationsClientsCreate = 'registrations.clients.create',
  RegistrationsClientsEdit = 'registrations.clients.edit',
  RegistrationsClientContactsCreate = 'registrations.clients.contacts.create',
  RegistrationsClientContactsEdit = 'registrations.clients.contacts.edit',
  RegistrationsClientLocationsCreate = 'registrations.clients.locations.create',
  RegistrationsClientLocationsEdit = 'registrations.clients.locations.edit',
  RegistrationsCategoriesRead = 'registrations.categories.read',
  RegistrationsCategoriesCreate = 'registrations.categories.create',
  RegistrationsCategoriesEdit = 'registrations.categories.edit',
  RegistrationsSubcategoriesCreate = 'registrations.categories.subcategories.create',
  RegistrationsSubcategoriesEdit = 'registrations.categories.subcategories.edit',
  RegistrationsItemsCreate = 'registrations.categories.items.create',
  RegistrationsItemsEdit = 'registrations.categories.items.edit',
  RegistrationsFinanceRead = 'registrations.finance.read',
  RegistrationsFinanceManage = 'registrations.finance.manage',

  LogisticsVehicleAgendaRead = 'logistics.vehicle-agenda.read',
  LogisticsVehicleAgendaManage = 'logistics.vehicle-agenda.manage',
  LogisticsExpensesRead = 'logistics.expenses.read',
  LogisticsExpensesManage = 'logistics.expenses.manage',
  LogisticsExpensesAdminRead = 'logistics.expenses.admin.read',
  LogisticsExpensesAdminManage = 'logistics.expenses.admin.manage',
  LogisticsExpensesApprove = 'logistics.expenses.approve',
  LogisticsExpensesPay = 'logistics.expenses.pay',
  LogisticsStatementsRead = 'logistics.statements.read',

  FinanceRead = 'finance.read',
  FinanceManage = 'finance.manage',

  CommercialRead = 'commercial.read',
  CommercialManage = 'commercial.manage',
}
