export enum AppPermission {
  SystemAdmin = 'system.admin',

  TicketsRead = 'tickets.read',
  TicketsCreate = 'tickets.create',
  TicketsEdit = 'tickets.edit',
  TicketsClassify = 'tickets.classify',
  TicketsExecute = 'tickets.execute',
  TicketsHold = 'tickets.hold',
  TicketsReject = 'tickets.reject',
  TicketsClose = 'tickets.close',
  TicketsAudit = 'tickets.audit',
  TicketsRadio = 'tickets.radio',

  CatalogTiRead = 'catalog.ti.read',
  CatalogTiManage = 'catalog.ti.manage',
  CatalogDevOpsRead = 'catalog.devops.read',
  CatalogDevOpsManage = 'catalog.devops.manage',

  UsersRead = 'users.read',
  UsersCreate = 'users.create',
  UsersEdit = 'users.edit',
  UsersManageAccess = 'users.manage-access',

  RegistrationsClientsRead = 'registrations.clients.read',
  RegistrationsClientsCreate = 'registrations.clients.create',
  RegistrationsClientsEdit = 'registrations.clients.edit',
  RegistrationsClientContactsCreate = 'registrations.clients.contacts.create',
  RegistrationsClientContactsEdit = 'registrations.clients.contacts.edit',
  RegistrationsClientLocationsCreate = 'registrations.clients.locations.create',
  RegistrationsClientLocationsEdit = 'registrations.clients.locations.edit',
  RegistrationsCategoriesRead = 'registrations.categories.read',
  RegistrationsCategoriesCreate = 'registrations.categories.create',
  RegistrationsCategoriesEdit = 'registrations.categories.edit',
  RegistrationsSubcategoriesCreate = 'registrations.categories.subcategories.create',
  RegistrationsSubcategoriesEdit = 'registrations.categories.subcategories.edit',
  RegistrationsItemsCreate = 'registrations.categories.items.create',
  RegistrationsItemsEdit = 'registrations.categories.items.edit',
  RegistrationsFinanceRead = 'registrations.finance.read',
  RegistrationsFinanceManage = 'registrations.finance.manage',

  LogisticsVehicleAgendaRead = 'logistics.vehicle-agenda.read',
  LogisticsVehicleAgendaManage = 'logistics.vehicle-agenda.manage',
  LogisticsExpensesRead = 'logistics.expenses.read',
  LogisticsExpensesManage = 'logistics.expenses.manage',
  LogisticsExpensesAdminRead = 'logistics.expenses.admin.read',
  LogisticsExpensesAdminManage = 'logistics.expenses.admin.manage',
  LogisticsExpensesApprove = 'logistics.expenses.approve',
  LogisticsExpensesPay = 'logistics.expenses.pay',

  FinanceRead = 'finance.read',
  FinanceManage = 'finance.manage',

  CommercialRead = 'commercial.read',
  CommercialManage = 'commercial.manage',
}
