CREATE DATABASE IF NOT EXISTS `nivel3`
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

CREATE DATABASE IF NOT EXISTS `mkt`
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

CREATE DATABASE IF NOT EXISTS `n3rd`
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;
